name: Daily Stock Check & Notify

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    # 使用Cron表达式定义定时任务
    # 此处设置为每天UTC时间01:00运行 (北京/台北时间上午9:00)
    - cron: "0 1 * * *"

jobs:
  run-stock-watcher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests

      - name: Execute Python script
        run: python main.py
        env:
          # 将GitHub Secrets中的机密信息注入到环境变量中
          WECHAT_APP_ID: ${{ secrets.WECHAT_APP_ID }}
          WECHAT_APP_SECRET: ${{ secrets.WECHAT_APP_SECRET }}
          WECHAT_USER_OPENID: ${{ secrets.WECHAT_USER_OPENID }}
          WECHAT_TEMPLATE_ID: ${{ secrets.WECHAT_TEMPLATE_ID }}
